version: "3.5"
services:
  app:
    build: .
    container_name: vite-react-express
    command: yarn dev
    image: vite-react-express:latest
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - .:/app
